// ============================================================
//  MOUNTAIN DATABASE — 8 regions × 5 levels × (popular + niche)
// ============================================================

const REGIONS = {
  hokkaido:   { name:"北海道", prefs:["北海道"] },
  tohoku:     { name:"東北", prefs:["青森県","岩手県","宮城県","秋田県","山形県","福島県"] },
  kanto:      { name:"関東", prefs:["茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県"] },
  chubu:      { name:"中部・北陸", prefs:["新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県"] },
  kansai:     { name:"関西", prefs:["三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県"] },
  chugoku:    { name:"中国", prefs:["鳥取県","島根県","岡山県","広島県","山口県"] },
  shikoku:    { name:"四国", prefs:["徳島県","香川県","愛媛県","高知県"] },
  kyushu:     { name:"九州・沖縄", prefs:["福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"] },
};

function getRegionByPref(pref) {
  for (const [key, val] of Object.entries(REGIONS)) {
    if (val.prefs.includes(pref)) return key;
  }
  return "kanto";
}

// headerColors per level
const LEVEL_COLORS = {
  entry: "#388e3c",
  beginner: "#2e7d32",
  intermediate: "#f57f17",
  advanced: "#d84315",
  expert: "#6a1b9a",
};

const LEVEL_META = {
  entry:        { level:"入門", badgeClass:"level-entry",        message:"まずは自然の中を歩く楽しさを体感しましょう。舗装路や遊歩道が中心で、スニーカーでも楽しめるコースです。" },
  beginner:     { level:"初級", badgeClass:"level-beginner",     message:"登山靴を用意して、少し本格的なハイキングに挑戦してみましょう。整備された登山道で、無理なく達成感を味わえます。" },
  intermediate: { level:"中級", badgeClass:"level-intermediate", message:"しっかり体力をつけた今、歩きごたえのある山に挑戦しましょう。山小屋利用やロングコースで、登山の奥深さを体感できます。" },
  advanced:     { level:"上級", badgeClass:"level-advanced",     message:"本格的な山岳地帯に足を踏み入れましょう。岩稜帯や長大な縦走路で、山のスケール感と達成感を存分に味わえます。" },
  expert:       { level:"エキスパート", badgeClass:"level-expert", message:"あなたの卓越した体力と経験なら、日本の山岳のあらゆるフィールドが舞台です。険しい岩稜、深い山域、そして伝説の難路へ。" },
};

// ============================================================
//  MOUNTAIN DATA BY REGION
// ============================================================

const mountainDB = {

// ==================== 北海道 ====================
hokkaido: {
  entry: {
    popular: [
      { name:"藻岩山（札幌市）", difficulty:"入門", time:"約2時間", elevation:"531m", season:"5月〜11月",
        tags:[{t:"札幌の展望台",c:"tag-view"},{t:"ロープウェイ併用可",c:"tag-highlight"}],
        description:"札幌市街を一望できる市民の山。ロープウェイやケーブルカーもあり、5つの登山道から選べます。山頂の夜景は日本新三大夜景の一つ。",
        tips:"慈恵会コースは原始林の中を歩く変化に富んだルート。エゾリスに会えることも。" },
      { name:"円山（札幌市）", difficulty:"入門", time:"約1時間", elevation:"225m", season:"4月〜11月",
        tags:[{t:"都市近郊",c:"tag-highlight"},{t:"原始林",c:"tag-nature"}],
        description:"地下鉄から徒歩で行ける天然記念物の原始林。山頂からは札幌市街と大通公園を一望。北海道神宮と合わせて散策できます。",
        tips:"春のカタクリの群落は見事。シマエナガが高確率で観察できるバードウォッチングの名所。" },
    ],
    niche: [
      { name:"嵐山（旭川市）", niche:true, difficulty:"入門", time:"約1.5時間", elevation:"253m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"北邦野草園",c:"tag-nature"},{t:"アイヌ文化",c:"tag-highlight"}],
        description:"旭川の隠れた展望スポット。山頂の展望台からは大雪山連峰の大パノラマが広がり、麓の北邦野草園ではエゾノリュウキンカなど北海道固有の植物を観察できる。",
        tips:"アイヌ文化の森・伝承のコタンが隣接。自然と文化を同時に楽しめる穴場です。" },
    ],
  },
  beginner: {
    popular: [
      { name:"樽前山（苫小牧市）", difficulty:"初級", time:"約3時間", elevation:"1,041m", season:"6月〜10月",
        tags:[{t:"活火山",c:"tag-highlight"},{t:"溶岩ドーム",c:"tag-view"}],
        description:"7合目まで車で行ける手軽さ。山頂の溶岩ドームは迫力満点で、支笏湖や太平洋を一望。高山植物も豊富で変化に富んだ登山が楽しめます。",
        tips:"イワブクロの花期（7月）は山全体が紫に染まる。風が強いので防風対策は必須。" },
      { name:"旭岳ロープウェイ周辺（東川町）", difficulty:"初級", time:"約2〜3時間", elevation:"姿見の池1,600m付近", season:"6月〜9月",
        tags:[{t:"大雪山の入口",c:"tag-highlight"},{t:"高山植物",c:"tag-nature"}],
        description:"ロープウェイで一気に標高1,600mへ。姿見の池周辺の散策路は高山植物の宝庫で、本格登山をしなくても大雪山の雰囲気を味わえます。",
        tips:"9月中旬の紅葉は日本一早い。赤・黄・緑のパッチワークは圧巻の一言。" },
    ],
    niche: [
      { name:"三角山〜大倉山縦走（札幌市）", niche:true, difficulty:"初級", time:"約3時間", elevation:"311m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"札幌市内縦走",c:"tag-highlight"},{t:"ジャンプ台展望",c:"tag-view"}],
        description:"札幌市内にいながら本格的な縦走気分を味わえる。三角山から大倉山ジャンプ台の展望台まで稜線を歩く都市型トレイル。",
        tips:"大倉山のリフトで山頂展望台に上がると、ジャンプ台の急斜面越しに札幌市街を一望。下山後は円山エリアのカフェへ。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"旭岳（東川町）", difficulty:"中級", time:"約5〜6時間", elevation:"2,291m", season:"7月〜9月",
        tags:[{t:"北海道最高峰",c:"tag-highlight"},{t:"日本百名山",c:"tag-highlight"}],
        description:"大雪山系の主峰で北海道最高峰。ロープウェイで姿見駅まで行き、山頂を目指す。広大な高山帯と噴気孔の景観はまさに「神々の遊ぶ庭」。",
        tips:"山頂から間宮岳→中岳温泉（野湯）→裾合平の周回コースは花と展望の黄金ルート。" },
      { name:"十勝岳（美瑛町・上富良野町）", difficulty:"中級", time:"約6〜7時間", elevation:"2,077m", season:"7月〜9月",
        tags:[{t:"活火山",c:"tag-highlight"},{t:"荒涼たる火山景観",c:"tag-view"}],
        description:"望岳台から荒々しい火山地帯を登る。噴煙を上げる火口と、振り返れば富良野の大地。火山と花畑のコントラストが劇的。",
        tips:"山頂直下の溶岩帯はガスに注意。晴れた日は大雪山〜トムラウシの大縦走路が一望。" },
    ],
    niche: [
      { name:"ニセイカウシュッペ山（上川町）", niche:true, difficulty:"中級", time:"約5時間", elevation:"1,883m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"大雪山の隠れ名峰",c:"tag-highlight"},{t:"大槍の岩峰",c:"tag-view"}],
        description:"大雪山系の中でも登山者が少ない秘峰。山頂付近の「大槍」と呼ばれる岩峰は圧巻で、表大雪の全貌を見渡せる展望は通好み。",
        tips:"林道が長いがその分静か。山頂から見る旭岳〜トムラウシの稜線は写真家憧れの構図。" },
      { name:"芦別岳（富良野市）", niche:true, difficulty:"中級〜上級", time:"約7〜8時間", elevation:"1,726m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"旧道の岩稜帯",c:"tag-highlight"},{t:"夫婦岩",c:"tag-view"}],
        description:"新道は花の山、旧道は本格的な岩稜帯という二面性を持つ山。雲峰山からの岩稜歩きは北海道離れしたアルペンムード。",
        tips:"旧道の鎖場は北海道の低山では屈指の本格派。新道→旧道の周回がおすすめ。" },
    ],
  },
  advanced: {
    popular: [
      { name:"トムラウシ山（新得町）", difficulty:"上級", time:"1泊2日", elevation:"2,141m", season:"7月〜9月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"奥座敷の秘峰",c:"tag-view"}],
        description:"大雪山系の奥座敷。日帰りは健脚者向けで片道約6時間。ロックガーデンや日本庭園と呼ばれる高山帯の美しさは北海道随一。",
        tips:"短縮登山口利用が一般的だが、林道状況は要確認。ヒサゴ沼避難小屋泊で余裕ある行程がおすすめ。" },
      { name:"幌尻岳（平取町）", difficulty:"上級", time:"2泊3日", elevation:"2,052m", season:"7月〜9月",
        tags:[{t:"日高山脈の盟主",c:"tag-highlight"},{t:"渡渉あり",c:"tag-highlight"}],
        description:"日高山脈の最高峰で百名山。額平川の渡渉を繰り返すアプローチが最大の核心。カールに広がるお花畑は感動的。",
        tips:"渡渉は水量次第で危険度が大きく変化。新冠ルートは渡渉なしだが長い。山小屋は完全予約制。" },
    ],
    niche: [
      { name:"カムイエクウチカウシ山（中札内村）", niche:true, difficulty:"上級", time:"2泊3日", elevation:"1,979m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"日高の核心部",c:"tag-highlight"},{t:"八ノ沢カール",c:"tag-nature"}],
        description:"日高山脈の核心部に位置し、百名山の幌尻岳以上に困難とされる。八ノ沢カールの花畑は日高の秘宝。渡渉・藪漕ぎ・ヒグマ対策が必須。",
        tips:"通称「カムエク」。日高の洗礼を受けるならこの山。入山者は非常に少なく真の秘境体験。" },
    ],
  },
  expert: {
    popular: [
      { name:"大雪山縦走 旭岳〜トムラウシ（東川町〜新得町）", difficulty:"エキスパート", time:"3泊4日", elevation:"最高2,291m", season:"7月〜8月",
        tags:[{t:"日本最長の高山縦走路",c:"tag-highlight"},{t:"神々の遊ぶ庭",c:"tag-view"}],
        description:"約40kmに及ぶ日本最長の高山帯縦走路。お鉢平・忠別岳・化雲岳など2,000m級の稜線を行く壮大な旅。避難小屋とテント泊で繋ぐ。",
        tips:"天候急変とヒグマに常に注意。水場が限られるので計画的な補給が不可欠。" },
    ],
    niche: [
      { name:"ペテガリ岳（浦河町・大樹町）", niche:true, difficulty:"エキスパート", time:"2〜3泊", elevation:"1,736m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"日高山脈最深部",c:"tag-highlight"},{t:"遥かなる山",c:"tag-nature"}],
        description:"「遥かなる山」の異名を持つ日高山脈最深部の秘峰。どのルートからも長大なアプローチが必要で、日本の一般登山で最もアクセスが困難な山の一つ。",
        tips:"西尾根ルートが最短だが藪漕ぎは覚悟。天馬街道側の神威山荘起点も選択肢。" },
      { name:"日高山脈 幌尻岳〜戸蔦別岳縦走", niche:true, difficulty:"エキスパート", time:"3泊4日", elevation:"最高2,052m", season:"7月〜8月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"七つ沼カール",c:"tag-view"},{t:"日高の真髄",c:"tag-highlight"}],
        description:"幌尻岳から戸蔦別岳へ続く稜線は日高山脈の核心部。途中の七つ沼カールは日高の宝石と称される絶景。エスケープルートがなく完全な自立行動が必要。",
        tips:"テント装備一式と数日分の食料を担ぐ覚悟が必要。天候を見極めた入山が命を守る。" },
    ],
  },
},

// ==================== 東北 ====================
tohoku: {
  entry: {
    popular: [
      { name:"青葉山（仙台市）", difficulty:"入門", time:"約1時間", elevation:"203m", season:"通年",
        tags:[{t:"仙台の裏山",c:"tag-highlight"},{t:"東北大植物園",c:"tag-nature"}],
        description:"仙台城跡の裏手にある都市近郊の山。東北大学植物園を通る散策路は四季折々の植物が楽しめ、仙台市街を見渡せます。",
        tips:"伊達政宗の騎馬像と合わせて歴史散策に。新緑の5月がおすすめ。" },
      { name:"八幡平 山頂散策（秋田県・岩手県境）", difficulty:"入門", time:"約1〜2時間", elevation:"1,613m", season:"6月〜10月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"ドラゴンアイ",c:"tag-season"}],
        description:"アスピーテラインで山頂駐車場まで車でアクセス。山頂周辺の木道散策は高層湿原と池塘の美しさを手軽に楽しめます。",
        tips:"5月下旬〜6月上旬の「ドラゴンアイ」（鏡沼の雪解け）はSNSで話題の絶景。" },
    ],
    niche: [
      { name:"太平山（秋田市）", niche:true, difficulty:"入門", time:"約2時間", elevation:"1,170m（旭又口から山頂）", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"ブナの原生林",c:"tag-nature"},{t:"秋田市民の山",c:"tag-highlight"}],
        description:"秋田市民に愛される里山だが県外の知名度は低い。旭又登山口からのブナ林は東北有数の美しさ。山頂の三吉神社奥宮は霊験あらたか。",
        tips:"秋のブナの黄葉は錦絵のよう。麓の太平山リゾート公園の温泉で汗を流せます。" },
    ],
  },
  beginner: {
    popular: [
      { name:"蔵王山 お釜周辺（山形県・宮城県）", difficulty:"初級", time:"約2〜3時間", elevation:"1,841m", season:"5月〜10月",
        tags:[{t:"エメラルドの火口湖",c:"tag-view"},{t:"ロープウェイ",c:"tag-highlight"}],
        description:"蔵王ハイラインで刈田岳駐車場へ。五色に変化するお釜は神秘的。熊野岳まで足を延ばせば蔵王連峰の最高峰に立てます。",
        tips:"早朝のお釜は風がなく鏡のように美しい。冬は樹氷観賞も名物。" },
      { name:"磐梯山（福島県）", difficulty:"初級", time:"約4〜5時間", elevation:"1,816m", season:"5月〜10月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"会津のシンボル",c:"tag-view"}],
        description:"八方台登山口からが最短ルート。山頂からは猪苗代湖と裏磐梯の湖沼群が一望。明治の大噴火で形成された荒々しい火口壁も見どころ。",
        tips:"裏磐梯側の銅沼（あかぬま）は五色沼より静かで神秘的な隠れスポット。" },
    ],
    niche: [
      { name:"泉ヶ岳（仙台市）", niche:true, difficulty:"初級", time:"約3時間", elevation:"1,175m", season:"4月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"仙台市民の秘密の山",c:"tag-highlight"},{t:"水神コース",c:"tag-nature"}],
        description:"仙台市内から車で40分の手軽さで本格登山が楽しめる。水神コースは沢沿いの涼やかなルートで、ブナ林の美しさは東北でもトップクラス。",
        tips:"春のカタクリ→夏の沢歩き→秋の紅葉→冬のスキーと四季すべて楽しめる万能の山。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"月山（山形県）", difficulty:"中級", time:"約5時間", elevation:"1,984m", season:"6月〜10月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"出羽三山",c:"tag-nature"}],
        description:"出羽三山の主峰。リフトで8合目付近まで行け、なだらかな稜線歩きが楽しめる。山頂の月山神社は修験道の聖地。",
        tips:"7月でも残雪の上を歩く箇所あり。弥陀ヶ原湿原のニッコウキスゲは夏の風物詩。" },
      { name:"岩手山（岩手県）", difficulty:"中級", time:"約7〜8時間", elevation:"2,038m", season:"6月〜10月",
        tags:[{t:"南部富士",c:"tag-view"},{t:"日本百名山",c:"tag-highlight"}],
        description:"岩手のシンボル「南部富士」。柳沢コースは火山礫の急登が続くが、山頂からの360度展望と巨大な火口は圧巻。",
        tips:"馬返し登山口の旧道は岩場のある変化に富んだルート。新道より面白いと評判。" },
    ],
    niche: [
      { name:"船形山（宮城県・山形県境）", niche:true, difficulty:"中級", time:"約5〜6時間", elevation:"1,500m", season:"6月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"東北のブナ原生林",c:"tag-nature"},{t:"静寂の稜線",c:"tag-highlight"}],
        description:"奥羽山脈の名峰だが登山者は少なく、東北最大級のブナの原生林を静かに歩ける。山頂からは月山・鳥海山・蔵王を一望する贅沢な展望。",
        tips:"大滝キャンプ場からの周回ルートが人気。秋の紅葉期でもほぼ貸し切り状態。" },
      { name:"焼石岳（岩手県・秋田県境）", niche:true, difficulty:"中級", time:"約6〜7時間", elevation:"1,548m", season:"6月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"東北随一の花の山",c:"tag-season"},{t:"ハクサンイチゲ大群落",c:"tag-nature"}],
        description:"東北屈指の花の名山だが交通の不便さから登山者は少ない。6月のハクサンイチゲの大群落は圧巻で、湿原と池塘が織りなす楽園的風景。",
        tips:"中沼コースが最短。つぶ沼コースはブナ林→湿原→花畑と変化に富み通好み。" },
    ],
  },
  advanced: {
    popular: [
      { name:"鳥海山（山形県・秋田県境）", difficulty:"上級", time:"約8〜9時間", elevation:"2,236m", season:"7月〜9月",
        tags:[{t:"出羽富士",c:"tag-view"},{t:"日本百名山",c:"tag-highlight"}],
        description:"東北第2位の高峰で日本海に面した独立峰。鳥海湖や万年雪渓、新山の溶岩ドームなど火山ならではの変化に富んだ景観が魅力。",
        tips:"鉾立→千蛇谷→新山→外輪山の周回がおすすめ。7月の大雪渓グリセードは爽快。" },
      { name:"飯豊山（福島県・山形県・新潟県境）", difficulty:"上級", time:"2泊3日", elevation:"2,105m", season:"7月〜9月",
        tags:[{t:"東北の秘峰",c:"tag-highlight"},{t:"日本百名山",c:"tag-highlight"}],
        description:"アプローチの長さが最大の障壁だが、稜線に出た瞬間の解放感は東北随一。ニッコウキスゲの大群落と雪渓のコントラストが感動的。",
        tips:"川入→切合小屋→本山小屋が定番。大日岳まで縦走すると飯豊の真の魅力がわかる。" },
    ],
    niche: [
      { name:"朝日連峰 以東岳（山形県）", niche:true, difficulty:"上級", time:"2泊3日", elevation:"1,772m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"東北の秘境縦走",c:"tag-highlight"},{t:"竜門山の稜線",c:"tag-view"}],
        description:"朝日連峰の北端に位置する秘峰。大朝日岳から以東岳への縦走路は東北で最も美しい稜線と称され、登山者は極めて少ない。",
        tips:"竜門山避難小屋付近の草原は天上の楽園。晴れた日に見る月山と日本海は生涯忘れられない光景。" },
    ],
  },
  expert: {
    popular: [
      { name:"飯豊連峰 全山縦走（福島県〜新潟県）", difficulty:"エキスパート", time:"4〜5泊", elevation:"最高2,128m", season:"7月〜8月",
        tags:[{t:"東北最難関の縦走路",c:"tag-highlight"},{t:"長大な稜線",c:"tag-view"}],
        description:"大日岳から飯豊本山、三国岳を経て弥平四郎へ抜ける東北最長の縦走路。残雪期は雪渓のトラバースが核心。東北の山の奥深さを知る旅。",
        tips:"水場の確認は入念に。避難小屋の管理人がいる時期を狙うのが安心。" },
    ],
    niche: [
      { name:"朝日連峰 古寺鉱泉〜大朝日岳〜以東岳 全縦走", niche:true, difficulty:"エキスパート", time:"3〜4泊", elevation:"最高1,871m", season:"7月〜8月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"東北随一の秘境縦走",c:"tag-highlight"},{t:"避難小屋泊",c:"tag-nature"}],
        description:"朝日連峰の全稜線を踏破する壮大な旅。人里から完全に隔絶された稜線は東北の山の原点。すべて避難小屋泊で自立した山行が求められる。",
        tips:"エスケープルートが限られるため、天候を見極めた入山が不可欠。寒暖差が激しい。" },
    ],
  },
},

// ==================== 関東 ====================
kanto: {
  entry: {
    popular: [
      { name:"高尾山 1号路（東京都）", difficulty:"入門", time:"約2時間", elevation:"599m", season:"通年",
        tags:[{t:"定番",c:"tag-highlight"},{t:"富士山展望",c:"tag-view"}],
        description:"都心から1時間弱。全面舗装の1号路はケーブルカーも併用可能。薬王院の参道を歩き、山頂から富士山を望めます。",
        tips:"冬の早朝は空気が澄んで富士山がくっきり。平日午前が空いていて狙い目。" },
      { name:"御岳山（東京都）", difficulty:"入門", time:"約2〜3時間", elevation:"929m", season:"通年",
        tags:[{t:"パワースポット",c:"tag-nature"},{t:"渓谷散策",c:"tag-view"}],
        description:"ケーブルカーで山上へ。武蔵御嶽神社やロックガーデンの苔むした渓谷美が見どころ。レンゲショウマの群生は都内最大級。",
        tips:"8月のレンゲショウマ祭りは森の妖精のような花が見られる隠れた名物。" },
    ],
    niche: [
      { name:"弘法山（神奈川県・秦野市）", niche:true, difficulty:"入門", time:"約2時間", elevation:"235m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"桜の名所",c:"tag-season"},{t:"富士山眺望",c:"tag-view"}],
        description:"秦野駅から歩ける低山ハイク。浅間山→権現山→弘法山を結ぶ稜線は展望抜群で、地元民以外にはあまり知られていない名コース。",
        tips:"権現山の展望台からは丹沢・富士・相模湾を一望。春は2,000本の桜のトンネル。" },
      { name:"衣張山（神奈川県・鎌倉市）", niche:true, difficulty:"入門", time:"約1.5時間", elevation:"121m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"鎌倉の裏山",c:"tag-nature"},{t:"海と富士の絶景",c:"tag-view"}],
        description:"鎌倉の観光ルートからは外れた超低山。山頂からは相模湾と富士山、鎌倉の街並みを同時に見渡せるビューポイント。",
        tips:"報国寺の竹林と組み合わせると最高。観光客はほぼゼロ。" },
    ],
  },
  beginner: {
    popular: [
      { name:"筑波山（茨城県）", difficulty:"初級", time:"約3〜4時間", elevation:"877m", season:"通年",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"ロープウェイ併用可",c:"tag-highlight"}],
        description:"百名山最低峰ながら奇岩群や360度展望が魅力。白雲橋コースは弁慶七戻りなどの奇岩を楽しめ、登山入門に最適。",
        tips:"冬の関東平野の夜景登山（ナイトハイク）が隠れた人気。" },
      { name:"金時山（神奈川県）", difficulty:"初級", time:"約3〜4時間", elevation:"1,212m", season:"3月〜12月",
        tags:[{t:"富士山展望No.1",c:"tag-view"},{t:"名物茶屋",c:"tag-highlight"}],
        description:"箱根外輪山の最高峰。山頂からの富士山は圧倒的なスケール。",
        tips:"金時茶屋のきのこ汁は名物。乙女峠側は比較的空いています。" },
    ],
    niche: [
      { name:"破風山（埼玉県・皆野町）", niche:true, difficulty:"初級", time:"約3時間", elevation:"627m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"秩父の隠れ名峰",c:"tag-view"}],
        description:"秩父の隠れた名山。猿岩の鎖場や風戸の岩場など低山とは思えないスリルがあり、山頂からは秩父盆地を一望。",
        tips:"麓の秩父華厳の滝はほとんど知られていない秘瀑。" },
      { name:"三浦アルプス（神奈川県）", niche:true, difficulty:"初級", time:"約4〜5時間", elevation:"最高214m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"海が見える稜線",c:"tag-view"},{t:"プチ縦走",c:"tag-highlight"}],
        description:"三浦半島の丘陵を縦走する隠れたトレイル。海を見ながらのアップダウンで首都圏とは思えない静けさ。",
        tips:"仙元山展望台から相模湾越しの富士山は隠れた絶景スポット。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"塔ノ岳（神奈川県・丹沢）", difficulty:"中級", time:"約6〜7時間", elevation:"1,491m", season:"4月〜11月",
        tags:[{t:"体力勝負",c:"tag-highlight"},{t:"富士山大パノラマ",c:"tag-view"}],
        description:"通称「バカ尾根」の大倉尾根は累積標高差1,200mの直登。山頂の尊仏山荘は通年営業。",
        tips:"表尾根ルートは鎖場と絶景の連続で変化に富む。" },
      { name:"日光白根山（群馬県）", difficulty:"中級", time:"約5〜6時間", elevation:"2,578m", season:"6月〜10月",
        tags:[{t:"関東以北最高峰",c:"tag-highlight"},{t:"五色沼",c:"tag-view"}],
        description:"ロープウェイで2,000m付近へ。山頂からは360度展望で、眼下の五色沼が印象的。",
        tips:"弥陀ヶ池→五色沼の周回は写真派必見。" },
    ],
    niche: [
      { name:"荒船山（群馬県・長野県境）", niche:true, difficulty:"中級", time:"約5時間", elevation:"1,423m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"テーブルマウンテン",c:"tag-highlight"},{t:"艫岩の断崖絶壁",c:"tag-view"}],
        description:"山頂部が平坦な独特の山容。艫岩の200m断崖から望む浅間山・八ヶ岳は息を呑む迫力。",
        tips:"山頂台地のブナ林は秋に黄金色のトンネルに。" },
      { name:"御座山（長野県・北相木村）", niche:true, difficulty:"中級", time:"約5〜6時間", elevation:"2,112m", season:"6月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"日本二百名山",c:"tag-highlight"},{t:"360度パノラマ",c:"tag-view"}],
        description:"情報が少ない秘峰。八ヶ岳・南北アルプス・富士山まで見渡せる山頂は訪れる人がごく少ない。",
        tips:"栗生コースが最短。山頂の岩場の展望は贅沢の一言。" },
    ],
  },
  advanced: {
    popular: [
      { name:"槍ヶ岳（長野県）", difficulty:"上級", time:"2泊3日", elevation:"3,180m", season:"7月〜9月",
        tags:[{t:"北アルプスの象徴",c:"tag-highlight"},{t:"穂先の岩場",c:"tag-view"}],
        description:"天を突く穂先は日本で最も美しいシルエットの山。上高地から入山し、最後の梯子と鎖で頂上に立つ瞬間は一生の思い出。",
        tips:"西鎌尾根からの裏ルートは通好みの素晴らしい稜線歩き。" },
      { name:"北岳（山梨県）", difficulty:"上級", time:"1泊2日", elevation:"3,193m", season:"7月〜9月",
        tags:[{t:"日本第2位の高峰",c:"tag-highlight"},{t:"高山植物の宝庫",c:"tag-nature"}],
        description:"南アルプスの盟主。草すべりルートは急登だが花が美しい。",
        tips:"キタダケソウは北岳だけの固有種。6月下旬〜7月上旬限定。" },
    ],
    niche: [
      { name:"笊ヶ岳（山梨県・静岡県境）", niche:true, difficulty:"上級", time:"日帰り10〜12時間 or 1泊2日", elevation:"2,629m", season:"6月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"南アルプスの秘峰",c:"tag-highlight"},{t:"富士山展望",c:"tag-view"}],
        description:"南アルプス深南部の秘峰。累積標高差2,400m超のハードルート。山頂から間近の聖岳・赤石岳は唯一無二。",
        tips:"布引山の稜線に出た瞬間の富士山ビューは忘れられない光景。" },
      { name:"平ヶ岳（新潟県・群馬県境）", niche:true, difficulty:"上級", time:"日帰り10〜11時間", elevation:"2,141m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"百名山最難関の一つ",c:"tag-highlight"},{t:"天上の楽園",c:"tag-nature"}],
        description:"百名山で最もアクセスが悪い秘峰。山頂の池塘群と高層湿原は天上の楽園。",
        tips:"鷹ノ巣登山口からの往復が正規ルート。" },
    ],
  },
  expert: {
    popular: [
      { name:"剱岳（富山県）", difficulty:"エキスパート", time:"2泊3日", elevation:"2,999m", season:"7月〜9月",
        tags:[{t:"岩と雪の殿堂",c:"tag-highlight"},{t:"カニのタテバイ",c:"tag-view"}],
        description:"日本の一般登山道で最難関。カニのタテバイ・ヨコバイが連続する別山尾根ルートは、すべての登山者の憧れ。",
        tips:"早月尾根は標高差2,200mの日帰り最難関ルート。" },
      { name:"大キレット（長野県）", difficulty:"エキスパート", time:"2〜3泊", elevation:"最高3,190m", season:"7月〜9月",
        tags:[{t:"日本三大キレット",c:"tag-highlight"},{t:"高度感MAX",c:"tag-view"}],
        description:"南岳〜北穂高岳を結ぶ日本屈指の岩稜帯。A沢のコル、飛騨泣き、長谷川ピークなど緊張感に溢れる。",
        tips:"南岳小屋→北穂高小屋の区間が核心。" },
    ],
    niche: [
      { name:"赤牛岳（富山県）", niche:true, difficulty:"エキスパート", time:"3泊4日", elevation:"2,864m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"読売新道",c:"tag-highlight"},{t:"北アルプス最深部",c:"tag-view"}],
        description:"水晶岳から延びる読売新道を行く北アルプス最深部の山。入山者が極めて少ない真の秘境ルート。",
        tips:"裏銀座→水晶岳→赤牛岳→黒部ダムの大縦走は最も贅沢な北アルプス。" },
      { name:"笈ヶ岳（石川県・岐阜県・富山県境）", niche:true, difficulty:"エキスパート", time:"日帰り12〜14時間 or 1泊2日", elevation:"1,841m", season:"4月下旬〜5月(残雪期限定)",
        tags:[{t:"穴場",c:"tag-niche"},{t:"登山道なしの幻の山",c:"tag-highlight"},{t:"残雪期限定",c:"tag-season"}],
        description:"一般登山道が存在せず、残雪期にのみアプローチできる「幻の山」。",
        tips:"中宮温泉からジライ谷経由が最もポピュラー。読図力が不可欠。" },
    ],
  },
},

// ==================== 中部・北陸 ====================
chubu: {
  entry: {
    popular: [
      { name:"戸隠森林植物園〜鏡池（長野県）", difficulty:"入門", time:"約2時間", elevation:"約1,200m（散策路）", season:"5月〜11月",
        tags:[{t:"戸隠連峰の絶景",c:"tag-view"},{t:"水芭蕉",c:"tag-season"}],
        description:"戸隠神社奥社の杉並木と、鏡池に映る戸隠連峰のリフレクションが美しい散策コース。登山装備不要で圧巻の山岳景観を楽しめます。",
        tips:"早朝の鏡池は風がなく水鏡に。5月の水芭蕉、10月の紅葉が特に見事。" },
      { name:"入笠山（長野県・富士見町）", difficulty:"入門", time:"約1.5時間", elevation:"1,955m", season:"4月〜11月",
        tags:[{t:"ゴンドラで楽々",c:"tag-highlight"},{t:"360度パノラマ",c:"tag-view"}],
        description:"ゴンドラで一気に山頂付近へ。山頂からは八ヶ岳・南北アルプス・富士山のパノラマ。入笠湿原のスズランは100万本の群落。",
        tips:"6月のスズランは日本随一の規模。冬はスノーシューも楽しめます。" },
    ],
    niche: [
      { name:"各務原アルプス（岐阜県）", niche:true, difficulty:"入門", time:"約2〜3時間", elevation:"最高383m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"ご当地アルプス",c:"tag-highlight"},{t:"濃尾平野展望",c:"tag-view"}],
        description:"岐阜県各務原市の低山群を繋ぐ稜線歩き。低山ながら展望が良く、濃尾平野から御嶽山まで一望。地元ではご当地アルプスとして親しまれている。",
        tips:"権現山→各務山→金山の縦走は変化に富む。地元のおばちゃんに会えたら道情報をゲット。" },
    ],
  },
  beginner: {
    popular: [
      { name:"霧ヶ峰・車山（長野県）", difficulty:"初級", time:"約3時間", elevation:"1,925m", season:"4月〜11月",
        tags:[{t:"ニッコウキスゲ",c:"tag-season"},{t:"なだらかな稜線",c:"tag-view"}],
        description:"車山肩から緩やかな草原を歩いて山頂へ。7月のニッコウキスゲの大群落は黄色い絨毯。八島ヶ原湿原との周回もおすすめ。",
        tips:"車山山頂のレーダードームは目印。八島湿原の夜明けは写真家の聖地。" },
      { name:"木曽駒ヶ岳（長野県）", difficulty:"初級", time:"約4時間", elevation:"2,956m", season:"7月〜9月",
        tags:[{t:"ロープウェイで3000m級",c:"tag-highlight"},{t:"千畳敷カール",c:"tag-view"}],
        description:"駒ヶ岳ロープウェイで千畳敷カールへ。そこから約2時間で3,000m級の山頂に立てる手軽さが魅力。",
        tips:"千畳敷カールの紅葉は9月下旬。混雑回避は始発ロープウェイが必須。" },
    ],
    niche: [
      { name:"粟ヶ岳（新潟県・加茂市）", niche:true, difficulty:"初級", time:"約4時間", elevation:"1,293m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"越後の名峰",c:"tag-highlight"},{t:"ヒメサユリ",c:"tag-season"}],
        description:"新潟県民には馴染み深いが県外からの登山者は少ない。6月のヒメサユリの群落は東北〜新潟の限られた山でしか見られない希少な花。",
        tips:"加茂水源池側のルートが整備されている。山頂からの守門岳・越後三山の展望が素晴らしい。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"燕岳（長野県）", difficulty:"中級", time:"約7〜8時間", elevation:"2,763m", season:"7月〜9月",
        tags:[{t:"北アルプスの女王",c:"tag-highlight"},{t:"花崗岩のオブジェ",c:"tag-view"}],
        description:"合戦尾根は北アルプス三大急登の一つだが、合戦小屋のスイカが名物。白い花崗岩とコマクサの山頂部は別世界の美しさ。",
        tips:"燕山荘は日本一のホスピタリティと評判。ご来光とモルゲンロートは必見。" },
      { name:"白山（石川県・岐阜県境）", difficulty:"中級", time:"約8時間 or 1泊2日", elevation:"2,702m", season:"7月〜9月",
        tags:[{t:"日本三霊山",c:"tag-highlight"},{t:"高山植物の楽園",c:"tag-nature"}],
        description:"別当出合から砂防新道で室堂へ。お池めぐりで翠ヶ池などの火口湖を巡る。高山植物の種類は日本随一の豊かさ。",
        tips:"南竜ヶ馬場のテント場は星空が圧巻。お花松原はクロユリの大群落で通好み。" },
    ],
    niche: [
      { name:"毛無山（静岡県・山梨県境）", niche:true, difficulty:"中級", time:"約5〜6時間", elevation:"1,964m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"富士山至近の大展望",c:"tag-view"},{t:"武田信玄の金山",c:"tag-highlight"}],
        description:"朝霧高原の背後にそびえる急登の山。富士山との距離が近く圧倒的迫力なのに登山者は少ない。",
        tips:"山腹には武田信玄の金山跡。不動の滝の展望台は穴場フォトスポット。" },
      { name:"笙ヶ岳（岐阜県・三重県・滋賀県境）", niche:true, difficulty:"中級", time:"約5時間", elevation:"908m", season:"4月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"養老山地最高峰",c:"tag-highlight"},{t:"伊勢湾展望",c:"tag-view"}],
        description:"養老山地の最高峰だが登山道は不明瞭な箇所も多く、静かな山歩きが楽しめる。東海地方の知られざる名峰。",
        tips:"養老の滝と合わせて訪問がおすすめ。秋の紅葉期は養老公園が見事。" },
    ],
  },
  advanced: {
    popular: [
      { name:"槍ヶ岳（長野県）", difficulty:"上級", time:"2泊3日", elevation:"3,180m", season:"7月〜9月",
        tags:[{t:"北アルプスの象徴",c:"tag-highlight"},{t:"穂先の岩場",c:"tag-view"}],
        description:"天を突く穂先は日本最美のシルエット。槍沢ルートで上高地から入山し、最後の梯子と鎖で頂上に立つ感動は格別。",
        tips:"西鎌尾根からの裏ルートは通好みの素晴らしい稜線歩き。" },
      { name:"北岳（山梨県）", difficulty:"上級", time:"1泊2日", elevation:"3,193m", season:"7月〜9月",
        tags:[{t:"日本第2位",c:"tag-highlight"},{t:"キタダケソウ",c:"tag-nature"}],
        description:"南アルプスの盟主。広河原からの草すべりは急登だが花が美しい。",
        tips:"キタダケソウは6月下旬〜7月上旬限定。北岳だけの固有種。" },
    ],
    niche: [
      { name:"鹿島槍ヶ岳（長野県・富山県境）", niche:true, difficulty:"上級", time:"2泊3日", elevation:"2,889m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"双耳峰の貴公子",c:"tag-highlight"},{t:"カクネ里氷河",c:"tag-nature"}],
        description:"後立山連峰の盟主。北峰・南峰を結ぶ吊り尾根の稜線は絵画のよう。東面のカクネ里雪渓は日本最後の氷河。",
        tips:"爺ヶ岳からの縦走で種池山荘→冷池山荘がおすすめ。" },
      { name:"笊ヶ岳（山梨県・静岡県境）", niche:true, difficulty:"上級", time:"日帰り10〜12h or 1泊2日", elevation:"2,629m", season:"6月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"南アルプスの秘峰",c:"tag-highlight"},{t:"富士山展望",c:"tag-view"}],
        description:"南アルプス深南部の秘峰。累積標高差2,400m超。聖岳・赤石岳の大迫力と静寂は唯一無二。",
        tips:"布引山の稜線に出た瞬間の富士山ビューは生涯忘れられない。" },
    ],
  },
  expert: {
    popular: [
      { name:"剱岳（富山県）", difficulty:"エキスパート", time:"2泊3日", elevation:"2,999m", season:"7月〜9月",
        tags:[{t:"岩と雪の殿堂",c:"tag-highlight"},{t:"カニのタテバイ",c:"tag-view"}],
        description:"日本の一般登山道最難関。カニのタテバイ・ヨコバイが連続する別山尾根ルートは全登山者の憧れ。",
        tips:"早月尾根は標高差2,200mの日帰り最難関。" },
      { name:"大キレット（長野県）", difficulty:"エキスパート", time:"2〜3泊", elevation:"最高3,190m", season:"7月〜9月",
        tags:[{t:"日本三大キレット",c:"tag-highlight"},{t:"高度感MAX",c:"tag-view"}],
        description:"南岳〜北穂高岳間の日本屈指の岩稜帯。長谷川ピーク・飛騨泣きは緊張感に満ちる。",
        tips:"南岳小屋→北穂高小屋が核心。天候急変に備え予備日必須。" },
    ],
    niche: [
      { name:"赤牛岳 読売新道（富山県）", niche:true, difficulty:"エキスパート", time:"3泊4日", elevation:"2,864m", season:"7月〜9月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"北アルプス最深部",c:"tag-view"},{t:"読売新道",c:"tag-highlight"}],
        description:"水晶岳から延びる読売新道を行く北アルプス最深部。入山者が極めて少ない真の秘境。",
        tips:"裏銀座→水晶岳→赤牛岳→黒部ダムの大縦走は最も贅沢な北アルプス。" },
      { name:"池口岳（長野県・静岡県境）", niche:true, difficulty:"エキスパート", time:"日帰り10〜12h or 1泊2日", elevation:"2,392m", season:"6月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"深南部の帝王",c:"tag-highlight"},{t:"原始の森",c:"tag-nature"}],
        description:"南アルプス深南部の最奥。年間登山者数が極めて少ない秘境中の秘境。倒木や藪漕ぎを含む長大なルート。",
        tips:"登山道は踏み跡レベルの箇所もあり読図力が必須。" },
    ],
  },
},

// ==================== 関西 ====================
kansai: {
  entry: {
    popular: [
      { name:"生駒山（大阪府・奈良県境）", difficulty:"入門", time:"約2時間", elevation:"642m", season:"通年",
        tags:[{t:"大阪の展望台",c:"tag-view"},{t:"ケーブルカー",c:"tag-highlight"}],
        description:"ケーブルカーで山上遊園地まで行ける手軽さ。ハイキングコースも整備され、大阪平野の夜景は百万ドルの価値。",
        tips:"暗峠ルートは日本一急勾配の国道を通る珍ルート。歴史好きにおすすめ。" },
      { name:"六甲山（兵庫県）", difficulty:"入門", time:"約2〜3時間", elevation:"931m", season:"通年",
        tags:[{t:"神戸の裏山",c:"tag-highlight"},{t:"1000万ドルの夜景",c:"tag-view"}],
        description:"ケーブルやロープウェイも利用可能。山上にはガーデンテラスや植物園があり、気軽に標高900mの世界を楽しめます。",
        tips:"有馬温泉への下山ルートは魚屋道が人気。温泉で締めくくるのが六甲流。" },
    ],
    niche: [
      { name:"交野山（大阪府・交野市）", niche:true, difficulty:"入門", time:"約1.5時間", elevation:"341m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"観音岩の巨石",c:"tag-highlight"},{t:"大阪平野一望",c:"tag-view"}],
        description:"大阪のベッドタウンにある知られざる展望の山。山頂の観音岩（巨大な一枚岩）に立つと、大阪平野から六甲山系まで一望。",
        tips:"源氏の滝→交野山→くろんど園地と繋ぐとプチ縦走気分に。地元民御用達の穴場。" },
    ],
  },
  beginner: {
    popular: [
      { name:"金剛山（大阪府・奈良県境）", difficulty:"初級", time:"約3時間", elevation:"1,125m", season:"通年",
        tags:[{t:"大阪最高峰",c:"tag-highlight"},{t:"登頂回数ボード",c:"tag-highlight"}],
        description:"大阪府最高峰で登山回数の記録板が名物。千早本道は初心者にも歩きやすく、冬には美しい霧氷が見られます。",
        tips:"山頂の登頂回数1万回超の常連さんとの交流も魅力。カトラ谷の花がきれい。" },
      { name:"大台ヶ原（奈良県・三重県境）", difficulty:"初級", time:"約3〜4時間", elevation:"1,695m", season:"4月〜11月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"日出ヶ岳",c:"tag-view"}],
        description:"駐車場からの東大台周回コースは整備された木道中心。大蛇嵓の断崖絶壁からの眺めは圧巻で、原始の苔の森も楽しめます。",
        tips:"西大台は事前予約制の立入規制区域。入ると手つかずの原始林が広がる秘境。" },
    ],
    niche: [
      { name:"ポンポン山（大阪府・京都府境）", niche:true, difficulty:"初級", time:"約3時間", elevation:"679m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"面白い山名",c:"tag-highlight"},{t:"福寿草群落",c:"tag-season"}],
        description:"ユニークな名前で知られるが登山者は意外と少ない。2月の福寿草の群落は知る人ぞ知る名物で、早春のお花見ハイクに最適。",
        tips:"善峯寺→ポンポン山→釈迦岳の縦走がおすすめ。山頂で足踏みするとポンポン響く。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"大峰山・八経ヶ岳（奈良県）", difficulty:"中級", time:"約6〜7時間", elevation:"1,915m", season:"5月〜10月",
        tags:[{t:"近畿最高峰",c:"tag-highlight"},{t:"世界遺産",c:"tag-highlight"}],
        description:"近畿地方の最高峰で修験道の聖地。弥山小屋を経由して八経ヶ岳へ。オオヤマレンゲ（7月）の群落は天女の花と呼ばれる。",
        tips:"行者還トンネル西口からが最短。弥山小屋で1泊すると余裕あるプランに。" },
      { name:"伯母子岳（和歌山県・奈良県境）", difficulty:"中級", time:"約5時間", elevation:"1,344m", season:"4月〜11月",
        tags:[{t:"小辺路",c:"tag-highlight"},{t:"世界遺産の古道",c:"tag-nature"}],
        description:"熊野古道小辺路の最高地点。歴史ある古道を歩きながら紀伊山地の展望を楽しむ。静かな山歩きができる。",
        tips:"高野山から十津川温泉まで歩き通す小辺路踏破は究極の古道歩き。" },
    ],
    niche: [
      { name:"三峰山（奈良県・三重県境）", niche:true, difficulty:"中級", time:"約4時間", elevation:"1,235m", season:"通年（冬の霧氷）",
        tags:[{t:"穴場",c:"tag-niche"},{t:"霧氷の名所",c:"tag-season"},{t:"八丁平",c:"tag-nature"}],
        description:"冬の霧氷で有名だが春〜秋は登山者が少なく静かな山歩きを楽しめる。山頂近くの八丁平は広大な草原で開放感抜群。",
        tips:"1〜2月の霧氷まつり期間は送迎バスあり。樹氷のトンネルは関西随一の美しさ。" },
      { name:"釈迦ヶ岳（奈良県）", niche:true, difficulty:"中級", time:"約5〜6時間", elevation:"1,800m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"大峰奥駈道",c:"tag-highlight"},{t:"釈迦如来像",c:"tag-view"}],
        description:"大峰奥駈道上の名峰だが、八経ヶ岳に比べ登山者は少ない。山頂の釈迦如来のブロンズ像と360度の展望が素晴らしい。",
        tips:"前鬼からの太古の辻ルートは修験道の雰囲気が色濃く残る。" },
    ],
  },
  advanced: {
    popular: [
      { name:"大峰奥駈道 吉野〜熊野（奈良県・和歌山県）", difficulty:"上級", time:"5〜7泊", elevation:"最高1,915m", season:"5月〜10月",
        tags:[{t:"世界遺産",c:"tag-highlight"},{t:"修験道の聖地",c:"tag-nature"}],
        description:"吉野山から熊野本宮大社まで約90kmの修験道。1300年の歴史を持つ日本最古の長距離トレイルの一つ。",
        tips:"靡（なびき）と呼ばれる行場が75ヶ所。通しで歩く場合は水場の確認が最重要。" },
    ],
    niche: [
      { name:"大普賢岳（奈良県）", niche:true, difficulty:"上級", time:"約7時間", elevation:"1,780m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"鎖場と梯子の連続",c:"tag-highlight"},{t:"奥駈道の核心部",c:"tag-view"}],
        description:"大峰山系の中でも最も険しい岩峰の一つ。日本岳→小普賢→大普賢の縦走は鎖場と梯子の連続で、大峰の本気を体感できる。",
        tips:"和佐又ヒュッテ起点の周回がおすすめ。笙ノ窟は修験者が籠る岩屋で神秘的。" },
    ],
  },
  expert: {
    popular: [
      { name:"大峰奥駈道 逆峯（熊野→吉野）全踏破", difficulty:"エキスパート", time:"6〜8泊", elevation:"最高1,915m", season:"5月〜10月",
        tags:[{t:"日本最古のロングトレイル",c:"tag-highlight"},{t:"修験の究極",c:"tag-nature"}],
        description:"順峯（吉野→熊野）より困難とされる逆峯での全踏破。南奥駈道は水場が極端に少なく、精神力と計画力が試される。",
        tips:"南奥駈道は行仙小屋〜玉置山間がキツい。水は1日3L以上の計画を。" },
    ],
    niche: [
      { name:"弥山川 双門ルート（奈良県）", niche:true, difficulty:"エキスパート", time:"約10〜12時間", elevation:"最高1,895m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"日本屈指の難ルート",c:"tag-highlight"},{t:"双門の滝",c:"tag-view"}],
        description:"近畿で最も危険なルートとされる弥山川遡行ルート。梯子・鎖・高巻きの連続で、途中の双門の滝（落差70m）は日本の滝百選。一般登山道だが実質バリエーション。",
        tips:"ルートファインディング能力が不可欠。単独行は非推奨。撤退の判断も重要。" },
    ],
  },
},

// ==================== 中国 ====================
chugoku: {
  entry: {
    popular: [
      { name:"宮島・弥山（広島県）", difficulty:"入門", time:"約2〜3時間", elevation:"535m", season:"通年",
        tags:[{t:"世界遺産",c:"tag-highlight"},{t:"瀬戸内海展望",c:"tag-view"}],
        description:"厳島神社とセットで楽しめる。ロープウェイで山上まで行き、霊火堂から山頂へ。瀬戸内海の多島美が一望。",
        tips:"消えずの火は1200年燃え続ける霊火。山頂の巨石群はパワースポット。" },
    ],
    niche: [
      { name:"三瓶山 女三瓶（島根県）", niche:true, difficulty:"入門", time:"約1.5時間", elevation:"957m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"山陰の名山",c:"tag-highlight"},{t:"草原の稜線",c:"tag-view"}],
        description:"三瓶山の一峰で、西の原からの散策路はなだらかな草原歩きが楽しい。日本海と大山を同時に望めるが県外の知名度は低い。",
        tips:"西の原の草原は「まるでスイス」と評判。放牧の牛とのどかな風景が広がる。" },
    ],
  },
  beginner: {
    popular: [
      { name:"大山（鳥取県）", difficulty:"初級", time:"約4〜5時間", elevation:"1,729m", season:"5月〜11月",
        tags:[{t:"伯耆富士",c:"tag-view"},{t:"日本百名山",c:"tag-highlight"}],
        description:"中国地方最高峰の独立峰。夏山登山道はブナ林→ダイセンキャラボクの群落→山頂と変化に富む。",
        tips:"元谷から見上げる北壁は日本離れした迫力。秋の紅葉は中国地方随一。" },
    ],
    niche: [
      { name:"蒜山三座縦走（岡山県）", niche:true, difficulty:"初級", time:"約5〜6時間", elevation:"最高1,202m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"蒜山高原",c:"tag-nature"},{t:"大山の展望台",c:"tag-view"}],
        description:"上蒜山→中蒜山→下蒜山を縦走するプチ縦走路。草原の稜線からは大山の全容が美しく、ジャージー牛の蒜山高原と合わせて楽しめる。",
        tips:"下山後は蒜山高原のジャージーソフトクリームが定番。中蒜山からの大山が絶景。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"三瓶山 周回（島根県）", difficulty:"中級", time:"約5〜6時間", elevation:"1,126m", season:"4月〜11月",
        tags:[{t:"日本二百名山",c:"tag-highlight"},{t:"火山の周回路",c:"tag-view"}],
        description:"男三瓶→子三瓶→孫三瓶→女三瓶の全峰周回。変化に富んだ火山地形と草原の稜線歩きは中国地方屈指の充実コース。",
        tips:"男三瓶の山頂からの日本海は絶景。室の内の火口跡はミステリアスな雰囲気。" },
    ],
    niche: [
      { name:"比婆山連峰（広島県）", niche:true, difficulty:"中級", time:"約5〜6時間", elevation:"1,264m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"イザナミの墓所伝説",c:"tag-highlight"},{t:"ブナの巨木群",c:"tag-nature"}],
        description:"日本神話のイザナミノミコトの墓所伝説が残る神秘的な山域。立烏帽子→池の段→比婆山の縦走はブナの巨木群が見事。",
        tips:"池の段のドウダンツツジの紅葉は知られざる絶景。10月中旬が見頃。" },
    ],
  },
  advanced: {
    popular: [
      { name:"大山 ユートピアルート（鳥取県）", difficulty:"上級", time:"約6〜7時間", elevation:"1,516m（三鈷峰）", season:"6月〜10月",
        tags:[{t:"花の稜線",c:"tag-season"},{t:"切り立つ北壁",c:"tag-view"}],
        description:"大山の裏側を行くルートで、三鈷峰への稜線は切れ落ちた崩壊地形の際を歩くスリル。ユートピア小屋周辺の花畑は絶品。",
        tips:"8月のお花畑は圧巻。砂すべりの下降は膝に注意。北壁の崩壊は現在進行形。" },
    ],
    niche: [
      { name:"吾妻山〜比婆山 全山縦走（広島県）", niche:true, difficulty:"上級", time:"約8〜9時間", elevation:"最高1,264m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"中国地方最長の縦走路",c:"tag-highlight"},{t:"神話の山々",c:"tag-nature"}],
        description:"休暇村吾妻山から比婆山連峰を全峰縦走する中国地方最長級のルート。神話の山々を繋ぐ壮大な稜線歩き。",
        tips:"ブナの紅葉期に歩くと黄金の回廊に。エスケープルートも確認しておくと安心。" },
    ],
  },
  expert: {
    popular: [
      { name:"大山 剣ヶ峰縦走路（鳥取県）※現在通行止め", difficulty:"エキスパート", time:"—", elevation:"1,729m", season:"—",
        tags:[{t:"伝説のルート",c:"tag-highlight"},{t:"崩壊で通行禁止",c:"tag-season"}],
        description:"かつて大山の最高峰・剣ヶ峰へ至った伝説の縦走路。稜線の崩壊が進み現在は通行禁止。日本の登山史に残る幻のルート。",
        tips:"弥山山頂からは往時の稜線の面影が見える。登山の歴史として語り継がれる存在。" },
    ],
    niche: [
      { name:"大山 振子沢〜ユートピア 周回（鳥取県）", niche:true, difficulty:"エキスパート", time:"約8〜9時間", elevation:"最高1,711m", season:"6月（残雪期）",
        tags:[{t:"穴場",c:"tag-niche"},{t:"残雪の大山",c:"tag-highlight"},{t:"上級者限定",c:"tag-view"}],
        description:"残雪期にのみ可能な振子沢からのルート。雪渓を詰めて稜線に出る達成感と、眼下に広がる日本海の展望は中国地方では味わえない本格的な山岳体験。",
        tips:"雪渓の状態は毎年異なる。アイゼン・ピッケルは必須。経験者同行が望ましい。" },
    ],
  },
},

// ==================== 四国 ====================
shikoku: {
  entry: {
    popular: [
      { name:"屋島（香川県）", difficulty:"入門", time:"約1.5時間", elevation:"293m", season:"通年",
        tags:[{t:"源平合戦の地",c:"tag-highlight"},{t:"瀬戸内海展望",c:"tag-view"}],
        description:"源平合戦の古戦場として有名なテーブル状の溶岩台地。遊歩道が整備され、山上からは瀬戸内海と高松市街を一望。",
        tips:"山上の屋島寺は四国八十八ヶ所の84番札所。夕日の瀬戸内は絶品。" },
    ],
    niche: [
      { name:"紫雲出山（香川県・三豊市）", niche:true, difficulty:"入門", time:"約1時間", elevation:"352m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"桜と瀬戸内海",c:"tag-season"},{t:"世界が注目",c:"tag-view"}],
        description:"米NYタイムズで取り上げられ海外で先に有名になった桜の名所。山頂展望台から見下ろす瀬戸内海の多島美は息を呑む。",
        tips:"4月上旬の桜×瀬戸内海は「死ぬまでに見たい絶景」。紫陽花の6月もおすすめ。" },
    ],
  },
  beginner: {
    popular: [
      { name:"剣山（徳島県）", difficulty:"初級", time:"約3時間", elevation:"1,955m", season:"5月〜11月",
        tags:[{t:"西日本第2位",c:"tag-highlight"},{t:"リフト併用可",c:"tag-highlight"}],
        description:"四国の最高峰級。リフトで中腹まで行け、山頂は笹原が広がるなだらかな稜線。次郎笈への縦走路は四国随一の展望。",
        tips:"剣山→次郎笈の稜線は天空の散歩道。修験道の聖地としての歴史も深い。" },
    ],
    niche: [
      { name:"寒風山（愛媛県・高知県境）", niche:true, difficulty:"初級", time:"約3時間", elevation:"1,763m", season:"5月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"石鎚山系の隠れ名峰",c:"tag-highlight"},{t:"桑瀬峠",c:"tag-view"}],
        description:"石鎚山系の中で地元登山者に人気だが県外の知名度は低い。桑瀬峠からの稜線は展望抜群で、石鎚山の全容が見渡せる。",
        tips:"伊予富士との縦走は四国を代表するブナ林歩きに。秋は黄金のトンネル。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"石鎚山（愛媛県）", difficulty:"中級", time:"約5〜6時間", elevation:"1,982m", season:"5月〜11月",
        tags:[{t:"西日本最高峰",c:"tag-highlight"},{t:"鎖場",c:"tag-highlight"}],
        description:"西日本最高峰で修験道の山。表参道の3本の鎖場は圧巻のスケール。天狗岳のナイフリッジは四国随一の高度感。",
        tips:"鎖場は迂回路あり。天狗岳は高度感があるが慎重に行けばOK。紅葉は10月中旬。" },
    ],
    niche: [
      { name:"東赤石山（愛媛県）", niche:true, difficulty:"中級", time:"約6〜7時間", elevation:"1,707m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"タカネバラ",c:"tag-season"},{t:"橄欖岩の山",c:"tag-nature"}],
        description:"四国で最も登山者の少ない名峰の一つ。日本最大のかんらん岩の露出がある地質学的にも貴重な山。6月のタカネバラは四国ではここだけ。",
        tips:"筏津登山口からの沢沿いのルートは涼しく快適。赤石山荘は無人小屋だが水場あり。" },
    ],
  },
  advanced: {
    popular: [
      { name:"石鎚山 東稜ルート（愛媛県）", difficulty:"上級", time:"約6〜7時間", elevation:"1,982m", season:"5月〜10月",
        tags:[{t:"四国最難関のルート",c:"tag-highlight"},{t:"南尖峰の岩場",c:"tag-view"}],
        description:"表参道とは別世界の本格的な岩稜ルート。南尖峰直下の岩場は高度感と緊張感に溢れ、山頂に立つと四国の山々が一望。",
        tips:"矢筈岩のトラバースが核心。経験者同行推奨。天狗岳への稜線は達成感満点。" },
    ],
    niche: [
      { name:"三嶺〜剣山 縦走（高知県・徳島県）", niche:true, difficulty:"上級", time:"1泊2日", elevation:"最高1,955m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"四国最高の縦走路",c:"tag-highlight"},{t:"笹原の稜線",c:"tag-view"}],
        description:"四国で最も美しいとされる縦走路。三嶺の笹原から剣山へ向かう約15kmの稜線はスケール感抜群。三嶺ヒュッテ泊が快適。",
        tips:"三嶺のコメツツジの紅葉（10月）は四国随一。名頃からのルートが最短。" },
    ],
  },
  expert: {
    popular: [
      { name:"石鎚山系 全山縦走（愛媛県）", difficulty:"エキスパート", time:"2〜3泊", elevation:"最高1,982m", season:"5月〜10月",
        tags:[{t:"四国の背骨",c:"tag-highlight"},{t:"長大な笹の稜線",c:"tag-view"}],
        description:"瓶ヶ森→石鎚山→堂ヶ森を繋ぐ石鎚山系の全山縦走。四国の背骨を歩き通す壮大な旅。水場が限られるのが核心。",
        tips:"UFOライン（町道瓶ヶ森線）のドライブと合わせて計画すると効率的。" },
    ],
    niche: [
      { name:"東赤石〜西赤石 縦走（愛媛県）", niche:true, difficulty:"エキスパート", time:"約10時間", elevation:"最高1,707m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"別子銅山の歴史",c:"tag-highlight"},{t:"アケボノツツジ",c:"tag-season"}],
        description:"法皇山脈の核心部を縦走するロングルート。東赤石の橄欖岩→八巻山の岩稜→西赤石のアケボノツツジと変化に富む。別子銅山の産業遺産も。",
        tips:"5月のアケボノツツジは西赤石の山肌をピンクに染める。銅山越の歴史遺構も必見。" },
    ],
  },
},

// ==================== 九州・沖縄 ====================
kyushu: {
  entry: {
    popular: [
      { name:"開聞岳 2合目散策（鹿児島県）", difficulty:"入門", time:"約1〜2時間", elevation:"924m（2合目付近まで）", season:"通年",
        tags:[{t:"薩摩富士",c:"tag-view"},{t:"ふれあい公園",c:"tag-highlight"}],
        description:"かいもん山麓ふれあい公園から2合目付近の散策路を歩く。美しい円錐形の開聞岳と池田湖を眺めながらの気軽なハイキング。",
        tips:"長崎鼻からの開聞岳ビューは定番の絶景ポイント。" },
      { name:"高千穂峰 御鉢周辺（宮崎県・鹿児島県境）", difficulty:"入門", time:"約2時間（御鉢まで）", elevation:"1,574m（御鉢）", season:"4月〜11月",
        tags:[{t:"天孫降臨の地",c:"tag-highlight"},{t:"火山景観",c:"tag-view"}],
        description:"天孫降臨神話の山。高千穂河原から御鉢の火口縁まではザレ場だが比較的短時間で火山景観を楽しめる。",
        tips:"御鉢の火口は圧巻のスケール。山頂の天の逆鉾はパワースポット。" },
    ],
    niche: [
      { name:"志賀島 潮見公園（福岡県）", niche:true, difficulty:"入門", time:"約1時間", elevation:"169m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"博多湾と玄界灘",c:"tag-view"},{t:"金印の島",c:"tag-highlight"}],
        description:"金印で有名な志賀島の最高地点。博多湾と玄界灘を同時に見渡せる展望台からの眺めは福岡市民にも意外と知られていない。",
        tips:"海の中道から志賀島まで繋がる砂州のドライブも最高。海鮮グルメとセットで。" },
    ],
  },
  beginner: {
    popular: [
      { name:"くじゅう連山・牧ノ戸峠コース（大分県）", difficulty:"初級", time:"約4時間", elevation:"1,786m（久住山）", season:"4月〜11月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"ミヤマキリシマ",c:"tag-season"}],
        description:"牧ノ戸峠から久住山への登山道は九州で最も登山者が多いポピュラーコース。6月のミヤマキリシマの大群落は山をピンクに染める。",
        tips:"久住山→中岳（九州本土最高峰）の周回がおすすめ。法華院温泉は秘湯の名湯。" },
      { name:"由布岳（大分県）", difficulty:"初級", time:"約4時間", elevation:"1,583m", season:"4月〜11月",
        tags:[{t:"豊後富士",c:"tag-view"},{t:"由布院温泉",c:"tag-highlight"}],
        description:"由布院のシンボル。正面登山口から東峰への登山道は整備されていて歩きやすい。下山後は由布院温泉で贅沢な時間を。",
        tips:"東峰は初心者OK。西峰への鎖場は中級者向け。秋のススキと紅葉が美しい。" },
    ],
    niche: [
      { name:"英彦山（福岡県・大分県境）", niche:true, difficulty:"初級", time:"約4時間", elevation:"1,199m", season:"通年",
        tags:[{t:"穴場",c:"tag-niche"},{t:"日本三大修験山",c:"tag-highlight"},{t:"銅の鳥居",c:"tag-nature"}],
        description:"日本三大修験山の一つだが、近年は登山者が減少。石段の表参道は歴史の重みを感じる。北岳→中岳→南岳の縦走は変化に富む。",
        tips:"奉幣殿の石段は修行気分。冬の霧氷も九州では貴重な体験。" },
    ],
  },
  intermediate: {
    popular: [
      { name:"阿蘇山・高岳（熊本県）", difficulty:"中級", time:"約5時間", elevation:"1,592m", season:"4月〜11月（火山活動による規制あり）",
        tags:[{t:"世界最大級カルデラ",c:"tag-highlight"},{t:"ミヤマキリシマ",c:"tag-season"}],
        description:"世界最大級のカルデラに聳える阿蘇五岳の最高峰。仙酔峡からの登山道は荒涼とした火山地帯を行く独特の体験。",
        tips:"火山活動の規制状況を必ず確認。根子岳のギザギザの山容は独特。" },
      { name:"祖母山（大分県・宮崎県境）", difficulty:"中級", time:"約6時間", elevation:"1,756m", season:"4月〜11月",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"原始林",c:"tag-nature"}],
        description:"祖母傾山系の盟主。アケボノツツジの時期は山全体がピンクに。原始林と苔むした巨木の森は屋久島にも匹敵する雰囲気。",
        tips:"北谷ルートが最短だが、神原ルートの原始林が通好み。" },
    ],
    niche: [
      { name:"傾山（大分県）", niche:true, difficulty:"中級〜上級", time:"約7〜8時間", elevation:"1,605m", season:"4月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"九州屈指の岩峰",c:"tag-highlight"},{t:"祖母傾の奥座敷",c:"tag-view"}],
        description:"祖母傾山系の奥座敷。九折登山口からの直登ルートは九州では珍しい本格的な岩場を含み、山頂の360度展望は四国まで見渡せることも。",
        tips:"坊主尾根の鎖場は九州のアルプスと呼ぶにふさわしい。三ツ尾からのコースは花が美しい。" },
    ],
  },
  advanced: {
    popular: [
      { name:"屋久島 宮之浦岳（鹿児島県）", difficulty:"上級", time:"1泊2日", elevation:"1,936m", season:"4月〜10月",
        tags:[{t:"九州最高峰",c:"tag-highlight"},{t:"世界自然遺産",c:"tag-highlight"}],
        description:"洋上のアルプスと称される屋久島の最高峰。淀川登山口から花崗岩の稜線を行く。屋久杉の巨木群と亜熱帯〜亜高山帯の植生変化が見事。",
        tips:"投石平の花崗岩のスラブは屋久島ならではの景観。新高塚小屋が快適。" },
      { name:"開聞岳（鹿児島県）", difficulty:"上級", time:"約5時間", elevation:"924m", season:"通年",
        tags:[{t:"日本百名山",c:"tag-highlight"},{t:"薩摩富士",c:"tag-view"}],
        description:"低山ながら累積標高差がありらせん状に登る独特のルート。山頂からは桜島、池田湖、東シナ海を一望。",
        tips:"2合目から上は一本道でエスケープ不可。夏は暑さ対策が重要。" },
    ],
    niche: [
      { name:"大崩山（宮崎県）", niche:true, difficulty:"上級", time:"約8〜9時間", elevation:"1,644m", season:"4月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"九州最後の秘境",c:"tag-highlight"},{t:"花崗岩の大岩壁",c:"tag-view"}],
        description:"九州で最も登山が困難な山。坊主尾根・湧塚尾根の花崗岩の大岩壁は圧巻のスケールで、梯子・ロープ・渡渉の連続。",
        tips:"上湧塚のテラスからの展望は九州屈指。テント泊で余裕ある計画を。" },
    ],
  },
  expert: {
    popular: [
      { name:"祖母傾 全山縦走（大分県・宮崎県）", difficulty:"エキスパート", time:"2泊3日", elevation:"最高1,756m", season:"4月〜10月",
        tags:[{t:"九州最難関の縦走路",c:"tag-highlight"},{t:"原始林の稜線",c:"tag-nature"}],
        description:"祖母山から傾山を経て大崩山まで繋ぐ九州最難関の縦走路。大崩山の岩場をフィナーレに据えたハードルート。",
        tips:"九折越避難小屋とテント泊を組み合わせる。水場の確認は入念に。" },
    ],
    niche: [
      { name:"屋久島 永田岳〜宮之浦岳〜黒味岳 縦走（鹿児島県）", niche:true, difficulty:"エキスパート", time:"2泊3日", elevation:"最高1,936m", season:"5月〜10月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"屋久島の核心部",c:"tag-highlight"},{t:"洋上アルプス",c:"tag-view"}],
        description:"屋久島の主稜線を全踏破する壮大なルート。永田岳の荒々しい岩峰から宮之浦岳の穏やかな稜線、黒味岳の花崗岩のスラブまで変化に富む。",
        tips:"永田歩道は整備が最低限で踏み跡程度の箇所も。天候急変と屋久島特有の大雨に注意。" },
      { name:"大崩山 湧塚尾根（宮崎県）", niche:true, difficulty:"エキスパート", time:"約9〜10時間", elevation:"1,644m", season:"4月〜11月",
        tags:[{t:"穴場",c:"tag-niche"},{t:"九州の岩の殿堂",c:"tag-highlight"},{t:"上湧塚テラス",c:"tag-view"}],
        description:"大崩山の中でも最も難しい湧塚尾根の完全周回。下湧塚→中湧塚→上湧塚の花崗岩の岩峰群を繋ぐルートは九州のヨセミテ。",
        tips:"ロープと梯子の連続だが、岩場好きにはたまらない。テント泊推奨。" },
    ],
  },
},

};  // end mountainDB

// ============================================================
//  NATURE STROLL DATABASE — 自然散策路（私服OK・観光と組み合わせ可）
// ============================================================

const strollDB = {

hokkaido: [
  { name:"北海道大学 イチョウ並木・ポプラ並木（札幌市）", difficulty:"散策", time:"約40分〜1時間", elevation:"平坦", season:"通年（紅葉：10月下旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"紅葉の名所",c:"tag-season"},{t:"観光ついでに",c:"tag-highlight"}],
    description:"札幌駅から徒歩圏内。380mのイチョウ並木が黄金に染まる秋は圧巻。クラーク像やエルム（ハルニレ）の森、中央ローンの芝生など構内全体が自然公園のよう。",
    tips:"秋の金葉祭（10月下旬）はライトアップも。学食でリーズナブルなランチも楽しめます。" },
  { name:"野幌森林公園（札幌市・江別市・北広島市）", difficulty:"散策", time:"約1〜2時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"原始林",c:"tag-nature"},{t:"エゾリス",c:"tag-highlight"}],
    description:"札幌近郊に残る2,053haの平地林。野幌の原始林は天然記念物に指定され、エゾリスやキツツキなど野生動物に出会える約20kmの遊歩道ネットワーク。",
    tips:"大沢口から百年記念塔エリアが歩きやすい。北海道開拓の村との組み合わせがおすすめ。" },
  { name:"知床五湖 高架木道（斜里町）", difficulty:"散策", time:"約30分（高架木道）", elevation:"平坦", season:"4月下旬〜11月",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"世界自然遺産",c:"tag-highlight"},{t:"知床連山",c:"tag-view"}],
    description:"世界自然遺産・知床の原生林に囲まれた五湖のうち一湖を高架木道で巡る。ヒグマの心配なく知床連山を映す湖面の絶景を楽しめる完全バリアフリーコース。",
    tips:"朝一番は湖面が鏡のように静か。展望台から羅臼岳のシルエットは圧巻。" },
  { name:"青い池・白ひげの滝 散策路（美瑛町）", difficulty:"散策", time:"約30分〜1時間", elevation:"平坦", season:"通年（冬はライトアップ）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"SNS映え",c:"tag-view"},{t:"美瑛観光",c:"tag-highlight"}],
    description:"アルミニウム成分で神秘的なコバルトブルーに輝く池と、白金温泉近くの白ひげの滝を結ぶ遊歩道。カラマツ林の中を歩く整備されたルート。",
    tips:"早朝は観光客が少なく水面が静か。冬のライトアップ（11月〜4月）は幻想的。" },
  { name:"函館山 旧登山道・つつじ山コース（函館市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"334m", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"夜景の山を散策",c:"tag-view"},{t:"歴史散策",c:"tag-highlight"}],
    description:"夜景で有名な函館山は昼間の散策路も魅力的。旧要塞跡や砲台跡を巡りながら津軽海峡と函館市街を一望。下山はロープウェイも利用可。",
    tips:"旧イギリス領事館からの散策開始がおすすめ。元町エリアの洋館巡りとセットで。" },
],

tohoku: [
  { name:"奥入瀬渓流（青森県・十和田市）", difficulty:"散策", time:"約2〜3時間", elevation:"ほぼ平坦", season:"4月〜11月（紅葉：10月中旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"渓流美の極致",c:"tag-nature"},{t:"観光ついでに",c:"tag-highlight"}],
    description:"十和田湖から流れ出る14kmの渓流沿いに整備された遊歩道。苔むした岩と無数の滝が織りなす渓谷美は日本屈指。車道と並行しているので好きな区間だけ歩ける。",
    tips:"石ヶ戸〜子ノ口間が見どころ凝縮。銚子大滝は必見。早朝は光芒が射して幻想的。" },
  { name:"中尊寺・毛越寺 浄土庭園散策（岩手県・平泉町）", difficulty:"散策", time:"約1.5〜2時間", elevation:"ほぼ平坦", season:"通年（紅葉：11月上旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"世界遺産",c:"tag-highlight"},{t:"浄土庭園",c:"tag-nature"}],
    description:"世界遺産・平泉の中尊寺参道の杉並木と毛越寺の浄土庭園を巡る。月見坂の木立のトンネルから金色堂へ、そして毛越寺の大泉が池の庭園美。",
    tips:"毛越寺の曲水の宴（5月）は平安貴族の雅な遊びを再現。秋の紅葉も見事。" },
  { name:"角館 武家屋敷通り・桧木内川堤（秋田県）", difficulty:"散策", time:"約1〜1.5時間", elevation:"平坦", season:"通年（桜：4月下旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"みちのくの小京都",c:"tag-highlight"},{t:"桜の名所",c:"tag-season"}],
    description:"角館の武家屋敷通りのシダレザクラと桧木内川堤のソメイヨシノを巡る散策路。黒板塀と桜のコントラストは東北随一の風情。",
    tips:"4月下旬の桜は日本有数の規模。冬の雪景色の武家屋敷もフォトジェニック。" },
  { name:"山寺・立石寺（山形県・山形市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"約250m（石段）", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"松尾芭蕉ゆかりの地",c:"tag-highlight"},{t:"絶壁の古刹",c:"tag-view"}],
    description:"「閑さや岩にしみ入る蝉の声」で知られる山寺。1,015段の石段を登りながら奇岩に建つ堂宇を巡る。五大堂からの山形盆地の眺望は絶景。",
    tips:"階段は段差が小さく歩きやすい。仙山線の車窓風景も素晴らしい。力こんにゃくが名物。" },
  { name:"松島 四大観・雄島散策（宮城県・松島町）", difficulty:"散策", time:"約1〜2時間", elevation:"ほぼ平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"日本三景",c:"tag-view"},{t:"島巡り",c:"tag-highlight"}],
    description:"日本三景・松島の260余島を眺める散策路。福浦橋で福浦島を巡り、雄島の苔むした石仏群を歩く。瑞巌寺の参道杉並木も見事。",
    tips:"遊覧船と組み合わせて多角的に松島を楽しむのがおすすめ。牡蠣シーズン（冬）は食も魅力。" },
],

kanto: [
  { name:"等々力渓谷（東京都・世田谷区）", difficulty:"散策", time:"約30分〜1時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"23区唯一の渓谷",c:"tag-nature"},{t:"都会のオアシス",c:"tag-highlight"}],
    description:"東京23区で唯一の渓谷。等々力駅から徒歩2分でアクセスでき、約1kmの遊歩道に湧水や不動の滝、日本庭園が点在。真夏でもひんやりした緑の空間。",
    tips:"渓谷入口の「ゴルフ橋」から下り、日本庭園→等々力不動尊と抜けるのが定番ルート。" },
  { name:"明治神宮の森（東京都・渋谷区）", difficulty:"散策", time:"約1時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"人工の原生林",c:"tag-nature"},{t:"都心の聖域",c:"tag-highlight"}],
    description:"100年前に計画的に植林された人工の森が、今や原始林のような生態系に成長。参道を歩くだけで都心にいることを忘れる深い森の空気を体感できる。",
    tips:"北参道→本殿→宝物殿→菖蒲田のルートは人が少なめ。6月の花菖蒲は必見。" },
  { name:"鎌倉 衣張山〜名越切通し（神奈川県）", difficulty:"散策", time:"約1.5〜2時間", elevation:"約120m", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"中世の古道",c:"tag-highlight"},{t:"海と富士山",c:"tag-view"}],
    description:"鎌倉の観光エリアから少し外れた静かな散策路。衣張山からは相模湾越しの富士山を望み、名越切通しでは鎌倉時代の古道の面影を感じられる。",
    tips:"報国寺の竹林→衣張山→名越切通し→逗子のルートが充実。観光客はほとんどいません。" },
  { name:"国営ひたち海浜公園 砂丘エリア散策（茨城県）", difficulty:"散策", time:"約1〜2時間", elevation:"平坦", season:"通年（ネモフィラ：4月、コキア：10月）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"花の丘",c:"tag-season"},{t:"SNS映え",c:"tag-view"}],
    description:"みはらしの丘のネモフィラ（春）やコキア（秋）で有名だが、太平洋を望む砂丘エリアの散策路も魅力的。松林や砂丘植物の自然海浜を歩ける。",
    tips:"4月中旬のネモフィラは開園直後の朝イチで。秋のコキアの紅葉グラデーションも見事。" },
  { name:"養老渓谷（千葉県・大多喜町）", difficulty:"散策", time:"約1〜2時間", elevation:"ほぼ平坦", season:"通年（紅葉：11月下旬〜12月上旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"関東一遅い紅葉",c:"tag-season"},{t:"渓谷美",c:"tag-nature"}],
    description:"房総半島の奥座敷。粟又の滝を中心に整備された遊歩道は約2kmの渓谷美を楽しめる。関東で最も遅い紅葉スポットとしても人気。",
    tips:"滝めぐり遊歩道は水辺を歩くので夏も涼しい。養老温泉の黒湯もおすすめ。" },
  { name:"長瀞 岩畳・秩父華厳の滝（埼玉県）", difficulty:"散策", time:"約1〜1.5時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"地学の宝庫",c:"tag-nature"},{t:"ライン下り",c:"tag-highlight"}],
    description:"天然記念物の岩畳は結晶片岩が織りなす自然のアート。荒川沿いの遊歩道を歩きながら「地球の窓」と呼ばれる地質の博物館を散策。",
    tips:"ライン下りやSLパレオエクスプレスとの組み合わせが人気。かき氷の阿左美冷蔵は行列覚悟。" },
],

chubu: [
  { name:"谷津山（静岡県・静岡市）", difficulty:"散策", time:"約40分〜1時間", elevation:"108m", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"街中の里山",c:"tag-nature"},{t:"富士山ビュー",c:"tag-view"}],
    description:"静岡市街の中心部に残る里山。住宅街から数分で森の中へ入り、山頂の愛宕神社からは富士山と駿河湾を一望。地元民の朝散歩コース。",
    tips:"古墳群も点在する歴史的にも貴重な場所。山頂は桜の隠れ名所。" },
  { name:"奥大井 夢の吊り橋・寸又峡（静岡県・川根本町）", difficulty:"散策", time:"約1〜1.5時間", elevation:"渓谷の遊歩道", season:"通年（紅葉：11月）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"エメラルドグリーンの湖",c:"tag-view"},{t:"秘境温泉",c:"tag-highlight"}],
    description:"寸又峡のエメラルドグリーンの湖面に架かる「夢の吊り橋」は世界的にも有名な絶景スポット。温泉街から遊歩道を歩いて周回できる。",
    tips:"吊り橋は一方通行で渡り切ると石段の登り。美女づくりの湯（寸又峡温泉）とセットで。" },
  { name:"上高地 大正池〜河童橋（長野県・松本市）", difficulty:"散策", time:"約1〜2時間", elevation:"平坦（約1,500m地点）", season:"4月下旬〜11月中旬",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"穂高連峰の絶景",c:"tag-view"},{t:"山岳リゾート",c:"tag-highlight"}],
    description:"日本を代表する山岳景勝地。大正池から梓川沿いの遊歩道を歩き、河童橋へ。穂高連峰と焼岳を間近に望む散策は登山装備不要の贅沢体験。",
    tips:"早朝の大正池の水鏡に映る穂高連峰は息を呑む美しさ。ウェストン碑周辺も静かで良い。" },
  { name:"兼六園・金沢城公園 散策（石川県・金沢市）", difficulty:"散策", time:"約1.5〜2時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"日本三名園",c:"tag-highlight"},{t:"加賀百万石",c:"tag-nature"}],
    description:"日本三名園の兼六園と隣接する金沢城公園を巡る散策路。ことじ灯籠、霞ヶ池、瓢池の庭園美と、復元された石垣と城門の歴史美を同時に楽しめる。",
    tips:"早朝の兼六園は無料開放（季節限定）で人も少なく最高。21世紀美術館とセットで。" },
  { name:"白川郷 荻町合掌造り集落散策（岐阜県）", difficulty:"散策", time:"約1〜2時間", elevation:"平坦", season:"通年（冬のライトアップ：1〜2月）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"世界遺産",c:"tag-highlight"},{t:"合掌造り",c:"tag-view"}],
    description:"世界遺産の合掌造り集落を自然の中で散策。荻町城跡展望台からの集落俯瞰は定番の絶景で、田園風景の中を歩く遊歩道は四季折々の表情を見せる。",
    tips:"城山展望台へは15分の散策路。冬のライトアップは完全予約制だが幻想的。" },
  { name:"柿田川湧水群（静岡県・清水町）", difficulty:"散策", time:"約30分〜1時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"東洋一の湧水",c:"tag-nature"},{t:"コバルトブルー",c:"tag-view"}],
    description:"富士山の雪解け水が約30年かけて湧き出す日本三大清流の一つ。第二展望台から覗くコバルトブルーの湧水は神秘的。国道沿いとは思えない自然空間。",
    tips:"井戸からの湧水は飲用可能。三島市街の源兵衛川水辺の道もセットで歩くと最高。" },
],

kansai: [
  { name:"哲学の道（京都府・京都市）", difficulty:"散策", time:"約30分〜1時間", elevation:"平坦", season:"通年（桜：4月上旬・紅葉：11月）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"京都の定番散策",c:"tag-highlight"},{t:"疏水沿い",c:"tag-nature"}],
    description:"銀閣寺から南禅寺へ琵琶湖疏水沿いに続く約2kmの散策路。桜並木と苔むした石垣の風情は京都を代表する散歩道。途中の法然院や大豊神社にも寄り道を。",
    tips:"早朝は人が少なく写真撮影のベストタイム。猫が多いことでも有名。" },
  { name:"箕面の滝道（大阪府・箕面市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"約100m", season:"通年（紅葉：11月下旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"大阪の奥座敷",c:"tag-nature"},{t:"紅葉の名所",c:"tag-season"}],
    description:"阪急箕面駅から箕面大滝（落差33m）まで約2.8kmの渓谷散策路。大阪市内から電車で30分とは思えない深い自然。日本の滝百選の箕面大滝は迫力満点。",
    tips:"紅葉の天ぷら（もみじの天ぷら）は箕面名物。サルに注意（食べ物を見せない）。" },
  { name:"春日山原始林（奈良県・奈良市）", difficulty:"散策", time:"約1.5〜2時間", elevation:"約200m", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"世界遺産",c:"tag-highlight"},{t:"千年の原始林",c:"tag-nature"}],
    description:"春日大社の背後に広がる世界遺産の原始林。1,000年以上人の手が入っていない貴重な照葉樹の森を、整備された遊歩道で巡れる。鹿にも会える。",
    tips:"東海自然歩道の一部。若草山山頂までの周回で奈良盆地の大展望も楽しめる。" },
  { name:"竹田城跡 雲海散策路（兵庫県・朝来市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"約350m", season:"通年（雲海：9〜11月早朝）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"天空の城",c:"tag-view"},{t:"石垣の絶景",c:"tag-highlight"}],
    description:"「日本のマチュピチュ」と称される天空の城跡。山城の郷から整備された散策路を登ると、雲海に浮かぶ石垣群の幻想的な風景が広がる。",
    tips:"雲海は秋の早朝が狙い目。立雲峡からの俯瞰ビューもおすすめ。" },
  { name:"熊野古道 大門坂〜那智大社（和歌山県）", difficulty:"散策", time:"約1〜1.5時間", elevation:"約130m", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"世界遺産",c:"tag-highlight"},{t:"苔の石段",c:"tag-nature"}],
    description:"熊野古道のハイライト区間を私服で手軽に体験。苔むした石段と杉の巨木のトンネルを抜けると那智大社と那智の滝。古道の雰囲気を最も手軽に味わえるルート。",
    tips:"大門坂入口の夫婦杉は樹齢800年。那智の滝（落差133m）は日本三名瀑の一つ。" },
  { name:"嵐山 竹林の小径・亀山公園（京都府・京都市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"ほぼ平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"竹林の名所",c:"tag-view"},{t:"保津川展望",c:"tag-highlight"}],
    description:"竹林の小径はインバウンドにも人気の定番だが、その先の亀山公園まで足を延ばすと保津峡を見下ろす静かな展望スポットに辿り着ける。",
    tips:"早朝7時前の竹林は人がほぼいない。天龍寺の庭園も早朝拝観がおすすめ。" },
],

chugoku: [
  { name:"縮景園（広島県・広島市）", difficulty:"散策", time:"約30分〜1時間", elevation:"平坦", season:"通年（梅：2月、桜：4月）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"大名庭園",c:"tag-nature"},{t:"被爆樹木",c:"tag-highlight"}],
    description:"広島藩主・浅野家の大名庭園。中国の西湖を模した回遊式庭園で、池の周りを巡る散策路から四季折々の景観を楽しめる。被爆樹木の生命力にも触れられる。",
    tips:"JR広島駅から徒歩10分。原爆ドーム・平和記念公園とセットで巡るのがおすすめ。" },
  { name:"出雲大社〜稲佐の浜 散策路（島根県・出雲市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"神話の地",c:"tag-highlight"},{t:"パワースポット",c:"tag-nature"}],
    description:"出雲大社の神域から命主社、真名井の清水を経て国譲り神話の舞台・稲佐の浜へ。神話の息吹を感じながら歩く古の道。",
    tips:"稲佐の浜の弁天島の夕日は格別。旧大社駅舎（重要文化財）も立ち寄りたい。" },
  { name:"倉敷美観地区・阿智の藤散策（岡山県・倉敷市）", difficulty:"散策", time:"約1〜2時間", elevation:"平坦", season:"通年（藤：4月下旬〜5月上旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"白壁の街並み",c:"tag-view"},{t:"藤の花",c:"tag-season"}],
    description:"白壁の蔵と柳の並木が美しい美観地区の散策。倉敷川沿いを歩き、大原美術館エリアから阿智神社の藤棚へ。鶴形山の自然遊歩道も静かで心地よい。",
    tips:"阿智神社の藤は推定樹齢300〜500年の天然記念物。小舟での川めぐりもおすすめ。" },
  { name:"秋芳洞・秋吉台カルスト台地（山口県・美祢市）", difficulty:"散策", time:"約1.5〜2時間", elevation:"ほぼ平坦（台地部）", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"日本最大の鍾乳洞",c:"tag-nature"},{t:"カルスト地形",c:"tag-view"}],
    description:"日本最大の鍾乳洞・秋芳洞の約1kmの洞内を歩き、地上に出ると広大なカルスト台地が広がる。白い石灰岩が点在する草原の散策路は日本離れした風景。",
    tips:"カルスト展望台からの眺めは絶景。長者ヶ森散策路は人が少なく静かに歩ける。" },
  { name:"鞆の浦 散策路（広島県・福山市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"ほぼ平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"潮待ちの港",c:"tag-highlight"},{t:"ノスタルジック",c:"tag-view"}],
    description:"江戸時代の港町の面影を残す鞆の浦。常夜灯や雁木、太田家住宅など歴史的建造物と瀬戸内海を眺めながらの散策は懐かしい日本の原風景。",
    tips:"対潮楼からの仙酔島ビューは「日東第一形勝」の絶景。渡船で仙酔島にも渡れる。" },
],

shikoku: [
  { name:"栗林公園（香川県・高松市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"平坦", season:"通年（紅葉：11月下旬）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"特別名勝",c:"tag-nature"},{t:"ミシュラン三つ星",c:"tag-highlight"}],
    description:"ミシュラン・グリーンガイドで三つ星を獲得した日本庭園。紫雲山を借景に6つの池と13の築山を配した回遊式庭園は、一歩一景の美しさ。",
    tips:"南庭の飛来峰からの眺めがベスト。和船に乗って水面から庭園を眺める体験もおすすめ。" },
  { name:"祖谷のかずら橋・祖谷渓散策（徳島県・三好市）", difficulty:"散策", time:"約1時間", elevation:"渓谷（階段あり）", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"秘境",c:"tag-nature"},{t:"スリル体験",c:"tag-highlight"}],
    description:"シラクチカズラで編まれた吊り橋を渡る秘境体験。足元から渓谷を覗くスリルと、エメラルドグリーンの祖谷川の美しさは四国随一。琵琶の滝も見どころ。",
    tips:"橋を渡った先のかずら橋キャンプ村の野猿（やえん）は手動ロープウェイ。奥祖谷の二重かずら橋は人が少なく穴場。" },
  { name:"桂浜・坂本龍馬記念館散策路（高知県・高知市）", difficulty:"散策", time:"約1時間", elevation:"ほぼ平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"太平洋の大展望",c:"tag-view"},{t:"龍馬ゆかりの地",c:"tag-highlight"}],
    description:"坂本龍馬像が見つめる桂浜は月の名所としても有名。浜辺から龍王岬の遊歩道を歩き、水族館や記念館エリアを巡る海辺の散策コース。",
    tips:"桂浜の「浜千鳥公園」からの夕日は絶景。高知日曜市とセットで計画すると充実。" },
  { name:"四万十川 沈下橋めぐり（高知県・四万十市）", difficulty:"散策", time:"約1〜2時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"最後の清流",c:"tag-nature"},{t:"沈下橋",c:"tag-view"}],
    description:"日本最後の清流・四万十川に架かる欄干のない沈下橋を渡りながら川沿いを散策。佐田沈下橋や岩間沈下橋など、それぞれ趣の異なる橋を巡る。",
    tips:"佐田沈下橋は最も下流で最も長い。レンタサイクルで巡るのも気持ちいい。" },
  { name:"道後温泉・道後公園散策（愛媛県・松山市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"ほぼ平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"日本最古の温泉",c:"tag-highlight"},{t:"湯の街風情",c:"tag-view"}],
    description:"道後温泉本館周辺のレトロな湯の街を散策し、道後公園（湯築城跡）の丘からは松山市街と石鎚山系を一望。正岡子規記念館も立ち寄れる。",
    tips:"道後温泉本館は改修後も入浴可能。商店街のみかんジュース蛇口は名物。" },
],

kyushu: [
  { name:"屋久島 白谷雲水峡 苔むす森（鹿児島県）", difficulty:"散策", time:"約1〜2時間（苔むす森まで往復）", elevation:"約100m", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"もののけの森",c:"tag-nature"},{t:"世界遺産",c:"tag-highlight"}],
    description:"映画『もののけ姫』の森のモデルとも言われる神秘的な苔の森。弥生杉コース〜苔むす森までは比較的歩きやすく、私服でも十分楽しめるエリア。",
    tips:"雨の日こそ苔が輝く。午前中の光が差し込む時間帯がベスト。足元は滑りやすいので注意。" },
  { name:"高千穂峡（宮崎県・高千穂町）", difficulty:"散策", time:"約1時間", elevation:"渓谷（階段あり）", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"柱状節理の渓谷",c:"tag-view"},{t:"神話の里",c:"tag-highlight"}],
    description:"阿蘇の火砕流が五ヶ瀬川に浸食されて生まれた柱状節理の渓谷。真名井の滝を中心に約1kmの遊歩道が整備され、貸しボートから見上げる渓谷美は圧巻。",
    tips:"貸しボートは午前中が待ち時間少ない。高千穂神社の夜神楽（毎晩20時）は必見。" },
  { name:"水前寺成趣園・江津湖散策（熊本県・熊本市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"湧水の庭園",c:"tag-nature"},{t:"東海道五十三次",c:"tag-highlight"}],
    description:"東海道五十三次を模した桃山式回遊庭園と、阿蘇の伏流水が湧き出す江津湖の水辺を散策。熊本市内で豊かな湧水の自然を体感できる。",
    tips:"水前寺から江津湖までは約1.5kmの散策路で繋がる。スイゼンジノリは世界でここだけの貴重種。" },
  { name:"柳川 川下りと水路散策（福岡県・柳川市）", difficulty:"散策", time:"約1〜2時間（川下り＋散策）", elevation:"平坦", season:"通年（柳の新緑：4月）",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"水郷の街",c:"tag-view"},{t:"北原白秋の故郷",c:"tag-highlight"}],
    description:"掘割（水路）が網の目のように張り巡らされた水郷の街。どんこ舟の川下りで水面から街を眺め、北原白秋の生家周辺の白壁の水路沿いを散策。",
    tips:"うなぎのせいろ蒸しは柳川名物。御花（旧柳川藩主別邸）の庭園も美しい。" },
  { name:"仙巌園・磯海岸（鹿児島県・鹿児島市）", difficulty:"散策", time:"約1〜1.5時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"桜島ビュー",c:"tag-view"},{t:"世界遺産",c:"tag-highlight"}],
    description:"島津家の別邸・仙巌園から桜島と錦江湾を望む絶景の庭園散策。世界遺産の旧集成館と合わせて、薩摩藩の歴史と自然を同時に楽しめる。",
    tips:"庭園から見る桜島は活火山が借景という世界的にも珍しい構図。両棒餅（ぢゃんぼ餅）が名物。" },
  { name:"青島・鬼の洗濯板（宮崎県・宮崎市）", difficulty:"散策", time:"約30分〜1時間", elevation:"平坦", season:"通年",
    tags:[{t:"散策路",c:"tag-stroll"},{t:"亜熱帯の島",c:"tag-nature"},{t:"奇岩",c:"tag-view"}],
    description:"周囲1.5kmの小さな島を取り囲む「鬼の洗濯板」（波状岩）は自然の芸術。亜熱帯植物に覆われた島内の青島神社は縁結びのパワースポット。",
    tips:"干潮時は洗濯板の上を歩ける。弥生橋から島への参道は南国ムード満点。" },
],

};  // end strollDB
